
name: Deploy iOS TestFlight

on:
  push

jobs:
  deploy:
    name: ${{ github.event.inputs.name }} deploy iOS TestFlight
    runs-on: [macOS, testflight]

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print user name
        shell: bash
        run: echo "${{ github.event.inputs.name }"
      - name: Print user name
        shell: bash
        run: echo "${{ github.event.inputs.log }"
