
name: Deploy iOS TestFlight

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: deploy iOS TestFlight
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Print user name
        shell: bash
        run: echo "${{ github.event.inputs }"
      # - name: Print user name
      #   shell: bash
      #   run: echo "${{ github.event.inputs.log }"
